### ISSUE TITLE
Where in custom fields fiter

### ISSUE THREAD

**Issue by crow131** [tbrethes/UpviseSDK#12]
Is there a way to filter by custom fields when searching? 
I'm using C# and your latest code base 

Example:
```
var where = "custom.F86='Notification'";
var jobs = query.select(Job.TABLE, where);
```

Best I could get was 
`var where = "custom like '%Notification%'";`

Thanks

**Comment by tbrethes** [comment]
Hi Kevin,

No you cannot because custom fields values are a big JSON string in the
"custom" SQL column.
You need to do a Query.select(), then loop and find the record matching
your custom fields filter on the client side.

Thanks

**Comment by crow131** [comment]
Ok thanks @tbrethes
