### ISSUE TITLE
The `.toJson().diff()`  extension does not appear to be implemented/accessible in beta 2.1

### ISSUE THREAD

**Issue by ashwinnair2011** [tbrethes/UpviseSDK#13]
The `.toJson().diff()`  extension does not appear to be implemented/accessible in beta 2.1 of the .Net client dll and is breaking the Samples project.

Working with beta2.0 

The functionality of `diff()` per a comment: // Use the diff() method of the JSONObject class to return only non identical values

**Comment by tbrethes** [comment]
Hi,
There is a new  UpviseClient DLL v2.1beta2 which adds the missing method
and has improvements for multithreading.

https://github.com/tbrethes/UpviseSDK/tree/master/Upvise%20Client%20Library/beta2.1

Thanks

**Comment by ashwinnair2011** [comment]
Thanks Thierry.

**Comment by tbrethes** [comment]
Please test then deploy the new DLL ASAP to improve traffic performance.
Cheers,
